### Testando o Cadastro de Usuário
POST http://localhost:3000/cadastro
Content-Type: application/json

{
  "nome": "João Silva",
  "email": "joao@email.com",
  "senha": "123",
  "tipo": "paciente"
}

###

### Testando o Login
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "joao@email.com",
  "senha": "123"
}
### Testando o Cadastro de Usuário
POST http://localhost:3000/cadastro
Content-Type: application/json

{
  "nome": "João Silva",
  "email": "joao@email.com",
  "senha": "123",
  "tipo": "paciente"
}

###

### Testando o Login
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "joao@email.com",
  "senha": "123"
}